name: kabadiwala_connect
description: Connecting kabadiwalas to authorized recyclers
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Local Offline Database (Hive)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Firebase Suite
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.2

  # Networking & Interceptors
  dio: ^5.7.0

  # Camera & Images
  camera: ^0.12.1
  image_picker: ^1.1.2

  # Location & Geocoding
  geolocator: ^13.0.1
  geocoding: ^5.0.0

  # Security & Compliance
  crypto: ^3.0.3
  permission_handler: ^11.3.1
  uuid: ^4.5.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_test: ^1.0.1

flutter:
  uses-material-design: true