class AppStrings {
  static const Map<String, Map<String, String>> translations = {
    'en': {
      'appTitle': 'Kabadiwala Connect',
      'greeting': 'Hello, Kabadiwala Connect!',
      'greetingMorning': 'Good morning',
      'greetingAfternoon': 'Good afternoon',
      'greetingEvening': 'Good evening',
      'subtitle': 'Ready to log today\'s collection?',
      'newCollection': 'New Collection',
      'newCollectionSub': 'Photograph and add items',
      'myLots': 'My Lots',
      'myLotsSub': 'View collection history',
      'totalLots': 'Total Lots',
      'totalValue': 'Est. Value',
    },
    'hi': {
      'appTitle': 'कबाड़ीवाला कनेक्ट',
      'greeting': 'नमस्ते, कबाड़ीवाला कनेक्ट!',
      'greetingMorning': 'सुप्रभात',
      'greetingAfternoon': 'नमस्कार',
      'greetingEvening': 'शुभ संध्या',
      'subtitle': 'आज का संग्रह दर्ज करने के लिए तैयार हैं?',
      'newCollection': 'नया संग्रह',
      'newCollectionSub': 'तस्वीर लें और वस्तुएं जोड़ें',
      'myLots': 'मेरे लॉट्स',
      'myLotsSub': 'संग्रह इतिहास देखें',
      'totalLots': 'कुल लॉट्स',
      'totalValue': 'अनुमानित मूल्य',
    },
    'mr': {
      'appTitle': 'कबाडीवाला कनेक्ट',
      'greeting': 'नमस्कार, कबाडीवाला कनेक्ट!',
      'greetingMorning': 'सुप्रभात',
      'greetingAfternoon': 'नमस्कार',
      'greetingEvening': 'शुभ संध्याकाळ',
      'subtitle': 'आजचा संग्रह नोंदवण्यासाठी तयार आहात?',
      'newCollection': 'नवीन संग्रह',
      'newCollectionSub': 'फोटो काढा आणि वस्तू जोडा',
      'myLots': 'माझे लॉट्स',
      'myLotsSub': 'संग्रह इतिहास पहा',
      'totalLots': 'एकूण लॉट्स',
      'totalValue': 'अंदाजित मूल्य',
    },
    'te': {
      'appTitle': 'కబాడీవాలా కనెక్ట్',
      'greeting': 'నమస్కారం, కబాడీవాలా కనెక్ట్!',
      'greetingMorning': 'శుభోదయం',
      'greetingAfternoon': 'శుభ మధ్యాహ్నం',
      'greetingEvening': 'శుభ సాయంత్రం',
      'subtitle': 'ఈరోజు సేకరణను నమోదు చేయడానికి సిద్ధంగా ఉన్నారా?',
      'newCollection': 'కొత్త సేకరణ',
      'newCollectionSub': 'ఫోటో తీసి వస్తువులను జోడించండి',
      'myLots': 'నా లాట్స్',
      'myLotsSub': 'సేకరణ చరిత్రను చూడండి',
      'totalLots': 'మొత్తం లాట్స్',
      'totalValue': 'అంచనా విలువ',
    },
    'ml': {
      'appTitle': 'കബാഡിവാല കണക്ട്',
      'greeting': 'നമസ്കാരം, കബാഡിവാല കണക്ട്!',
      'greetingMorning': 'സുപ്രഭാതം',
      'greetingAfternoon': 'ശുഭ മധ്യാഹ്നം',
      'greetingEvening': 'ശുഭ സന്ധ്യ',
      'subtitle': 'ഇന്നത്തെ ശേഖരണം രേഖപ്പെടുത്താൻ തയ്യാറാണോ?',
      'newCollection': 'പുതിയ ശേഖരണം',
      'newCollectionSub': 'ഫോട്ടോയെടുത്ത് ഇനങ്ങൾ ചേർക്കുക',
      'myLots': 'എന്റെ ലോട്ടുകൾ',
      'myLotsSub': 'ശേഖരണ ചരിത്രം കാണുക',
      'totalLots': 'ആകെ ലോട്ടുകൾ',
      'totalValue': 'ഏകദേശ മൂല്യം',
    },
    'ta': {
      'appTitle': 'கபாடிவாலா கனெக்ட்',
      'greeting': 'வணக்கம், கபாடிவாலா கனெக்ட்!',
      'greetingMorning': 'காலை வணக்கம்',
      'greetingAfternoon': 'மதிய வணக்கம்',
      'greetingEvening': 'மாலை வணக்கம்',
      'subtitle': 'இன்றைய சேகரிப்பை பதிவு செய்ய தயாரா?',
      'newCollection': 'புதிய சேகரிப்பு',
      'newCollectionSub': 'புகைப்படம் எடுத்து பொருட்களைச் சேர்க்கவும்',
      'myLots': 'எனது லாட்கள்',
      'myLotsSub': 'சேகரிப்பு வரலாற்றைக் காண்க',
      'totalLots': 'மொத்த லாட்கள்',
      'totalValue': 'மதிப்பிடப்பட்ட மதிப்பு',
    },
    'bho': {
      'appTitle': 'कबाड़ीवाला कनेक्ट',
      'greeting': 'प्रणाम, कबाड़ीवाला कनेक्ट!',
      'greetingMorning': 'सुप्रभात',
      'greetingAfternoon': 'नमस्कार',
      'greetingEvening': 'शुभ संझा',
      'subtitle': 'आजु के संग्रह दर्ज करे खातिर तइयार बानी?',
      'newCollection': 'नया संग्रह',
      'newCollectionSub': 'फोटो खींचीं आ सामान जोड़ीं',
      'myLots': 'हमार लॉट्स',
      'myLotsSub': 'संग्रह के इतिहास देखीं',
      'totalLots': 'कुल लॉट्स',
      'totalValue': 'अनुमानित मूल्य',
    },
    'gu': {
      'appTitle': 'કબાડીવાલા કનેક્ટ',
      'greeting': 'નમસ્તે, કબાડીવાલા કનેક્ટ!',
      'greetingMorning': 'સુપ્રભાત',
      'greetingAfternoon': 'નમસ્કાર',
      'greetingEvening': 'શુભ સાંજ',
      'subtitle': 'આજનો સંગ્રહ નોંધવા માટે તૈયાર છો?',
      'newCollection': 'નવો સંગ્રહ',
      'newCollectionSub': 'ફોટો પાડો અને વસ્તુઓ ઉમેરો',
      'myLots': 'મારા લોટ્સ',
      'myLotsSub': 'સંગ્રહ ઇતિહાસ જુઓ',
      'totalLots': 'કુલ લોટ્સ',
      'totalValue': 'અંદાજિત કિંમત',
    },
  };

  static const Map<String, String> languageNames = {
    'en': 'English',
    'hi': 'हिंदी',
    'mr': 'मराठी',
    'te': 'తెలుగు',
    'ml': 'മലയാളം',
    'ta': 'தமிழ்',
    'bho': 'भोजपुरी',
    'gu': 'ગુજરાતી',
  };

  static String get(String key, String languageCode) {
    return translations[languageCode]?[key] ?? key;
  }
}
