// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMjjmr6xV2zZB-l_Hy-_4UTZ4jdnUV32M',
    appId: '1:772665361823:web:0fdbe05592daa494b1e9aa',
    messagingSenderId: '772665361823',
    projectId: 'kabadiwalaconnect-8c8c4',
    authDomain: 'kabadiwalaconnect-8c8c4.firebaseapp.com',
    storageBucket: 'kabadiwalaconnect-8c8c4.firebasestorage.app',
    measurementId: 'G-JP24HGTLQY',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMjjmr6xV2zZB-l_Hy-_4UTZ4jdnUV32M',
    appId: '1:772665361823:web:0fdbe05592daa494b1e9aa',
    messagingSenderId: '772665361823',
    projectId: 'kabadiwalaconnect-8c8c4',
    authDomain: 'kabadiwalaconnect-8c8c4.firebaseapp.com',
    storageBucket: 'kabadiwalaconnect-8c8c4.firebasestorage.app',
    measurementId: 'G-JP24HGTLQY',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO6J2D82wL-InaO3CcDJRhceq61pSVsnY',
    appId: '1:772665361823:ios:954499407d146cb4b1e9aa',
    messagingSenderId: '772665361823',
    projectId: 'kabadiwalaconnect-8c8c4',
    storageBucket: 'kabadiwalaconnect-8c8c4.firebasestorage.app',
    iosBundleId: 'com.example.kabadiwalaConnect',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO6J2D82wL-InaO3CcDJRhceq61pSVsnY',
    appId: '1:772665361823:ios:954499407d146cb4b1e9aa',
    messagingSenderId: '772665361823',
    projectId: 'kabadiwalaconnect-8c8c4',
    storageBucket: 'kabadiwalaconnect-8c8c4.firebasestorage.app',
    iosBundleId: 'com.example.kabadiwalaConnect',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfvhy2YchvT57yoLsZeW6aj4URouxQY2w',
    appId: '1:772665361823:android:8df1257443dc151fb1e9aa',
    messagingSenderId: '772665361823',
    projectId: 'kabadiwalaconnect-8c8c4',
    storageBucket: 'kabadiwalaconnect-8c8c4.firebasestorage.app',
  );
}
